config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
 devise_scope :user do
    get '/users', to: 'devise/registrations#new'#新規登録失敗後の遷移先エラー対策
  end

    root to: 'homes#top'
    get "/about", to: "homes#about"

    resources :users, only:[:show, :edit, :update]

    # 一人用食材管理ルーティング
    resources :foods  do                            # 食材
      resources :comments, only:[:create, :destroy] # 食材コメント
    end

    # 複数人用食材管理ルーティング
    get '/groups/search', to: 'groups#search'
    get '/groups/join', to: 'groups#join'
    resources :groups, only:[:index, :create, :edit, :update, :destroy] do # グループ機能
      resources :share_foods, only:[:new, :index, :create, :show, :edit, :update, :destroy] do                             # 共有食材
        resources :share_comments, only:[:create, :destroy] # 共有食材コメント
      end
    end

    # その他追加機能
    resources :notices, only:[:index]                        # 通知一覧機能
    # 検索機能は他機能が完成後に設定
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :food
  # has_many :notices, dependent: :destroy
  
  validates :comment, presence: true, length: { in: 0..300 } 
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @food = Food.find(params[:food_id])
    comment = current_user.comments.new(comment_params)
    comment.food_id = @food.id
    if comment.save
      # redirect_to food_path(food), notice: 'コメントしました' #非同期化のためコメントアウト
    else
      redirect_to food_path(@food), alert: 'コメント出来ませんでした'
    end
  end
  
  def destroy
    Comment.find_by(id: params[:id]).destroy
    @food = Food.find(params[:food_id])
    # render :comments_destroy  #render先にjsファイルを指定でjsファイルの名称を変更しても使用できる。
    
    # redirect_to food_path(params[:food_id])　#非同期化の為コメントアウト
  end
  
  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
  <% food.comments.each do |comment| %>
    <div class="row rounded border shadow-sm text-wrap">
      <div class="col-1">
        <%= comment.created_at.strftime('%m/%d') %>
      </div>
      <div class="col-auto">
      <!--CSSに適応させるためPタグ使用-->
        <p><%= comment.comment %></p>
      </div>
      <% if comment.user == current_user %>
        <div class="col-1">
          <%= link_to "削除", food_comment_path(comment.food, comment), method: :delete, remote: true, data:{ confirm: '本当に削除しますか？', cancel: '取り消す',commit: '削除'}, title: '削除確認', class:"btn btn-outline-danger btn-sm mt-1 mb-1" %>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/comments/_new_comment.html.erb
<%= form_with(model:[food, comment], data: {remote: true}) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "例：カレーに使用します。使わないで！", class:"mb-1 form-control", required: true %>
  <%= f.submit "コメント追加" , class:"btn btn-dark btn-sm"%>
<% end %>

app/views/comments/create.js.erb
<!--id="comments_areaをrenderで指定した部分テンプレートに更新-->
$("#comments").html("<%= j(render 'comments/comments', food: @food, comment: @comment) %>");

<!--フォームを送信したあとにフォームの値を空にする-->
$("#comment_comment").val('');


$(".comment_success").css("display", "block");
$(".comment_alert").css("display", "block");

app/views/comments/destroy.js.erb
<!--id="commentsをrenderで指定した部分テンプレートに更新-->
$("#comments").html("<%= j(render 'comments/comments', food: @food, comment: @comment) %>");

<!--フォームを送信したあとにフォームの値を空にする-->
$("#comment_comment").val('');

$(".comment_alert").css("display", "block");
$(".comment_success").css("display", "none");