config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
 devise_scope :user do
    get '/users', to: 'devise/registrations#new'#新規登録失敗後の遷移先エラー対策
  end

    root to: 'homes#top'
    get "/about", to: "homes#about"

    resources :users, only:[:show, :edit, :update]

    # 一人用食材管理ルーティング
    resources :foods  do                            # 食材
      resources :comments, only:[:create, :destroy] # 食材コメント
    end

    # 複数人用食材管理ルーティング
    get '/groups/search', to: 'groups#search'
    get '/groups/join', to: 'groups#join'
    resources :groups, only:[:index, :create, :edit, :update, :destroy] do # グループ機能
      resources :share_foods, only:[:new, :index, :create, :show, :edit, :update, :destroy] do                             # 共有食材
        resources :share_comments, only:[:create, :destroy] # 共有食材コメント
      end
    end

    # その他追加機能
    resources :notices, only:[:index]                        # 通知一覧機能
    # 検索機能は他機能が完成後に設定
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  has_many :share_foods, dependent: :destroy
  has_many :share_comments, dependent: :destroy
  # has_many :notices, dependent: :destroy

  validates :name, presence: true, length: { maximum: 9 } , uniqueness: true

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :authenticate_user!
  before_action :group_find, only: [:show, :edit, :update, :correct_group]
  before_action :correct_group,only: [:edit]


  def index
    index_view
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      GroupUser.create(user_id: current_user.id,  group_id: @group.id)
      redirect_to groups_path, notice: 'グループを作成しました'
    else
      redirect_to groups_path, alert: 'グループを作成出来ませんでした'
    end
  end

  def show; end

  def edit; end

  def update
    if @group.update(group_params)
      redirect_to groups_path, notice: 'グループを更新しました'
    else
      redirect_to groups_path, alert: 'グループを更新出来ませんでした'
    end
  end

  def destroy
    delete_group = Group.find(params[:id])
    if delete_group.destroy
      redirect_to groups_path, notice: 'グループを削除しました'
    else
      redirect_to groups_path, alert: 'グループを削除出来ませんでした'
    end
  end

  def search
    keyword = params[:keyword]
    @results = Group.where('name LIKE ?', "%#{keyword}%")

    index_view

    render :index
  end

  def join
    group_id = params[:group_id].to_i
    group_user = GroupUser.find_by(user_id: current_user.id,  group_id: group_id)

    if group_user
      GroupUser.destroy(group_user.id)
      redirect_to groups_path , notice: 'グループを退室しました'
    else
      GroupUser.create(user_id: current_user.id,  group_id: group_id)
      redirect_to groups_path , info: 'グループに参加しました'
    end
  end

  def correct_group
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end


  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :owner_id,  user_ids: [])
  end

  def index_view
    @group = Group.new
    @group.users << current_user

    @group_lists = Group.all
    @group_joining = GroupUser.where(user_id: current_user.id)
    @group_lists_none = "グループに参加していません"
  end

  def group_find
    @group = Group.find(params[:id])
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<h3>グループ名の編集</h3>

<div>
  <!--グループ作成機能-->
  <%= form_with(model: @group, local: true) do |f| %>
    <div class="input-group mb-3" data-toggle="popover" data-placement="top" data-content="同じ名称のグループは作成できません  1~9文字まで">
      <%= f.text_field :name, type:"text", class:"form-control" %>
      <div class="input-group-append">
        <%= f.submit '更新', class: "btn btn-outline-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/index.html.erb
<h3 class="mb-4">管理者グループ</h3>

   <!--popover動作用js-->
  <%= render "layouts/popover" %>

<div>
  <!--グループ作成機能-->
  <%= form_with(model: @group, local: true) do |f| %>
    <div class="input-group mb-3" data-toggle="popover" data-placement="top" data-content="同じ名称のグループは作成できません  1~9文字まで">
      <%= f.text_field :name, type:"text", class:"form-control", placeholder:"管理者グループ新規作成", required: true %>
      <div class="input-group-append">
        <%= f.submit '-新規作成-', class: "btn btn-outline-primary" %>
      </div>
    </div>
  <% end %>
</div>

<div class="row mt-4">
  <div class="col-lg-7 order-1">
    <h4>参加中の管理者グループ</h4>
    <!--グループがあるかの判断とない場合の表示-->
    <% if @group_joining == [] %>
      <div class="alert alert-info"><%= @group_lists_none %></div>
    <% else %>
      <div  class="overflow-auto" style="height:510px;">
        <% @group_lists.each do |list| %>
          <!--参加しているグループがあるかの判断-->
          <% if list.user_ids.include?(current_user.id) %>
            <div class="row shadow mt-2 rounded border border-secondary-20 mr-1 mt-2 ml-1">
              <div class="col mt-1 mb-1 btn btn-sm btn-block">
                <%= list.name %> <span class="badge badge-secondary"><%= list.user_ids.count %></span>
              </div>

              <!--グループユーザーかの判断-->
              <% if GroupUser.exists?(group_id: list.id, user_id: current_user.id) %>
                <div class="col-sm-3 col-lg-3">
                  <%= link_to '管理へ', new_group_share_food_path(list.id), class: "btn btn-outline-dark mt-1 mb-1 btn-block rounded-pill" %>
                </div>
                <div class="col-sm-3 col-lg-2">
                  <%= link_to '退出', groups_join_path(group_id: list.id), class: "btn btn-outline-info mt-1 mb-1 btn-block" %>
                </div>
              <% end %>

              <!--グループオーナーのみ表示-->
              <% if list.owner_id == current_user.id %>
                <div class="col-sm-2 col-lg-2">
                  <%= link_to '編集', edit_group_path(list.id), method: :get, class: "btn btn-outline-warning mt-1 mb-1 btn-block" %>
                </div>
                <div class="col-sm-2 col-lg-2">
                  <%= link_to '削除', "/groups/#{list.id}", method: :delete, data:{ confirm: '本当に削除しますか？', cancel: '取り消す',commit: '削除'}, title: '削除確認', class: "btn btn-outline-danger mt-1 mb-1 btn-block" %>
                </div>
              <% else %>
                <div class="col-sm-2 col-lg-2"> </div>
                <div class="col-sm-2 col-lg-2"> </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="col-lg order-2 order-lg-2">
    <div class="row mt-4 ml-3">
      <!--グループ検索機能-->
      <%= form_with url: groups_search_path, method: :get, local: true  do |f| %>
        <div class="input-group mb-3">
          <%= f.text_field :keyword, placeholder: "グループ検索", class: "form-control" %>
          <div class="input-group-append">
            <%= f.submit '検索', class: "btn btn-outline-secondary" %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="overflow-auto" style="height:470px;">
      <% if @results %>
        <% @results.each do |result| %>
          <div>
            <div class="row rounded border border-secondary-20">
              <div class="col btn mt-1 mb-1 btn-sm btn-block">
                <%= result.name %> <span class="badge badge-secondary"><%= result.user_ids.count %></span>
              </div>

             <!--グループユーザーかの判断-->
              <% if GroupUser.exists?(group_id: result.id, user_id: current_user.id) %>
                <div class="col-sm-3 col-lg-2">
                  <%= link_to '退出', groups_join_path(group_id: result.id), class: "btn btn-outline-info mt-1 mb-1 btn-sm btn-block" %>
                </div>
              <% else %>
                <div class="col-sm-3 col-lg-2">
                  <%= link_to '参加', groups_join_path(group_id: result.id), class: "btn btn-outline-success mt-1 mb-1 btn-sm btn-block rounded-pill" %>
                </div>
              <% end %>

              <!--グループオーナーのみ表示-->
              <% if result.owner_id == current_user.id %>
                <div class="col-sm-2 col-lg-2">
                  <%= link_to '編集', edit_group_path(result.id), method: :get, class: "btn btn-outline-warning mt-1 mb-1 btn-sm btn-block" %>
                </div>
                <div class="col-sm-2 col-lg-2 mr-2">
                  <%= link_to '削除', "/groups/#{result.id}", method: :delete, data:{ confirm: '本当に削除しますか？', cancel: '取り消す',commit: '削除'}, title: '削除確認', class: "btn btn-outline-danger mt-1 mb-1 btn-sm btn-block" %>
                </div>
              <% else %>
                <div class="col-sm-2 col-lg-2"> </div>
                <div class="col-sm-2 col-lg-2 mr-2"> </div>
              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="alert alert-info">こちらから検索してグループに参加できます</div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<h3>管理者リスト　-　<%= @group.name %></h3>

<div>
  <% @group.users.each do |user| %>
    <h3>
      <%= user.name %>
      <% if @group.owner_id == user.id %>
        <span class="badge badge-success">owner</span>
      <% end %>
    </h3>
  <% end %>
</div>