config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
 devise_scope :user do
    get '/users', to: 'devise/registrations#new'#新規登録失敗後の遷移先エラー対策
  end

    root to: 'homes#top'
    get "/about", to: "homes#about"

    resources :users, only:[:show, :edit, :update]

    # 一人用食材管理ルーティング
    resources :foods  do                            # 食材
      resources :comments, only:[:create, :destroy] # 食材コメント
    end

    # 複数人用食材管理ルーティング
    get '/groups/search', to: 'groups#search'
    get '/groups/join', to: 'groups#join'
    resources :groups, only:[:index, :create, :edit, :update, :destroy] do # グループ機能
      resources :share_foods, only:[:new, :index, :create, :show, :edit, :update, :destroy] do                             # 共有食材
        resources :share_comments, only:[:create, :destroy] # 共有食材コメント
      end
    end

    # その他追加機能
    resources :notices, only:[:index]                        # 通知一覧機能
    # 検索機能は他機能が完成後に設定
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  has_many :share_foods, dependent: :destroy
  has_many :share_comments, dependent: :destroy
  # has_many :notices, dependent: :destroy

  validates :name, presence: true, length: { maximum: 9 } , uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :destroy
  has_many :comments, dependent: :destroy
  # has_many :notices, dependent: :destroy

  #共有管理用アソシエーション
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  attachment :profile_image #プロフィール画像用
  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 15 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :user_find, only: [:show, :edit, :update, :correct_user]
  before_action :correct_user,only: [:edit]
  
  def show
    @group_lists = Group.all
    @group_joining = GroupUser.where(user_id: @user.id)
    @group_lists_none = "グループに参加していません"
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: '管理者情報を更新しました。'
    else
      render :edit
    end
  end
  
  def correct_user
    unless @user.id == current_user.id
      redirect_to user_path(@user.id)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :email)
  end
  
  def user_find
    @user = User.find(params[:id])
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h3 class="offset-2">プロフィール</h3>

<div class="col-8 offset-2 mt-5">
  <%= form_with model: @user, local: true do |f| %>

    <div class="form-group row">
      <div class="col-4"><%= f.label :ProfileImage %></div>
      <div class="col-8"><%= f.attachment_field :profile_image %></div>
    </div>

    <div class="form-group row mt-3">
      <div class="col-4"><%= f.label :Name %></div>
      <div class="col-8"><%= f.text_field :name, class:"form-control" %></div>
    </div>

    <div class="form-group row mt-3">
      <div class="col-4"><%= f.label :Email %></div>
      <div class="col-8"><%= f.text_field :email, class:"from-control" %></div>
    </div>

    <div class="text-center mt-5">
      <%= f.submit "更新", class: "btn btn-outline-success", style: "width:120px" %>
    </div>

  <% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm col-lg-4 mt-3 shadow-lg rounded mr-2 order-1">
    <h3 class="text-center mt-1">管理者プロフィール</h3>
    <div class="row m-3">
      <div class="col"></div>
      <div class="col"><%= attachment_image_tag @user, :profile_image, :fill, 150, 150, format: 'jpeg', fallback: "no_image.jpg", class:"rounded-circle img-thumbnail" %></div>
    </div>
    <div class="row mt-2">
      <div class="col text-center">名前</div>
      <div class="col text-center font-italic"><%= @user.name%></div>
    </div>
    <% if @user.id == current_user.id %>
    <div class="row mt-2">
      <div class="col text-center">Email</div>
      <div class="col text-center"><%= @user.email %></div>
    </div>
    <div class="row mt-2 mb-2">
      <div class="col text-center"></div>
      <div class="col text-center">
        <p><%= link_to "プロフィール編集", edit_user_path(@user), class:"btn btn-outline-danger btn-sm mt-3" %></p>
      </div>
    </div>
    <% end %>

  </div>

<div class="col-lg mt-3 shadow-lg rounded order-2">
    <h4 class="text-center mt-2 mb-2">参加中の管理者グループ
      <%= link_to 'グループ画面へ', groups_path, class: "btn btn-outline-primary ml-5" %>
    </h4>
    <!--グループがあるかの判断とない場合の表示-->
    <% if @group_joining == [] %>
      <div class="alert alert-info"><%= @group_lists_none %></div>
    <% else %>
      <div  class="overflow-auto" style="height:300px;">
        <% @group_lists.each do |list| %>
          <!--参加しているグループがあるかの判断-->
          <% if list.user_ids.include?(@user.id) %>
            <div class="row shadow mt-2 rounded border border-secondary-20 mr-1 mt-2 ml-1">
              <div class="col btn mt-1 mb-1 btn-block">
                <%= list.name %> <span class="badge badge-secondary"><%= list.user_ids.count %></span>
              </div>

              <!--グループユーザーかの判断-->
              <% if GroupUser.exists?(group_id: list.id, user_id: current_user.id) %>
                <div class="col-sm-3 col-lg-2">
                  <%= link_to '管理へ', new_group_share_food_path(list.id), class: "btn btn-outline-dark mt-1 mb-1 btn-block rounded-pill" %>
                </div>
              <% else %>
                <div class="col-sm-3 col-lg-2"></div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>