config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
 devise_scope :user do
    get '/users', to: 'devise/registrations#new'#新規登録失敗後の遷移先エラー対策
  end

    root to: 'homes#top'
    get "/about", to: "homes#about"

    resources :users, only:[:show, :edit, :update]

    # 一人用食材管理ルーティング
    resources :foods  do                            # 食材
      resources :comments, only:[:create, :destroy] # 食材コメント
    end

    # 複数人用食材管理ルーティング
    get '/groups/search', to: 'groups#search'
    get '/groups/join', to: 'groups#join'
    resources :groups, only:[:index, :create, :edit, :update, :destroy] do # グループ機能
      resources :share_foods, only:[:new, :index, :create, :show, :edit, :update, :destroy] do                             # 共有食材
        resources :share_comments, only:[:create, :destroy] # 共有食材コメント
      end
    end

    # その他追加機能
    resources :notices, only:[:index]                        # 通知一覧機能
    # 検索機能は他機能が完成後に設定
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  has_many :share_foods, dependent: :destroy
  has_many :share_comments, dependent: :destroy
  # has_many :notices, dependent: :destroy

  validates :name, presence: true, length: { maximum: 9 } , uniqueness: true

end

app/views/layouts/_member-button.html.erb
<button type="button" class="btn btn-outline-secondary mb-1" data-toggle="modal" data-target="#modal1">
  <%= list.name %>
  <span class="badge badge-pill badge-secondary"><%= list.user_ids.count %></span>
</button>
<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="label1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="label1"><%= list.name %>-管理者リスト</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body overflow-auto" style="height:200px;">
        <% list.users.each do |member| %>
          <h4>
            <%= link_to user_path(member.id), class:"btn btn-light btn-block" do %>
              <%= member.name %>
              <% if list.owner_id == member.id %>
                <span class="badge badge-success badge-sm badge-pill">OWNER</span>
              <% end %>
            <% end %>
          </h4>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_popover.html.erb
<script>
(function() {
  window.addEventListener("turbolinks:load", function () {
    $('[data-toggle="popover"]').popover();
  });
})();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodStorage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
    <header class="shadow-lg">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div><%= link_to image_tag("logo2.PNG", size: "200x70"), root_path, class:"btn btn-outline-secondary"%></div>
          <% if current_page?(root_path) %>
            <div class="ml-5 mt-2"><%= link_to('動画を始めから見る', 'javascript:void(0);', onclick: "window.location.reload();", class: "btn btn-outline-success rounded-pill")  %></div>
          <% end %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse " id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="mt-sm-2 mr-1">
                  <%= link_to 'Profile', user_path(current_user.id), class:"btn btn-outline-primary btn-block btn-lg mb-1 font-italic" %>
                </li>
                <li class="mt-sm-2 mr-1">
                  <%= link_to "Storage", new_food_path, class:"btn btn-outline-warning btn-block btn-lg mb-1 font-italic" %>
                </li>
                <li class="mt-sm-2 mr-1">
                  <%= link_to "Share-Storage", groups_path, class:"btn btn-outline-danger btn-block btn-lg mb-1 font-italic" %>
                </li>
                <li class="mt-sm-2 mr-1">
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-outline-dark btn-block btn-lg font-italic" %>
                </li>
              <% else %>
                <li class="mt-sm-2 mr-1">
                  <%= link_to "About", about_path, class:"btn btn-outline-secondary btn-block btn-lg mb-1 font-italic" %>
                </li>
                <!--<li class="btn btn-outline-success mb-1">-->
                <!--  なんか考えます-->
                <!--</li>-->
                <li class="mt-sm-2 mr-1">
                  <%= link_to "Sign up", new_user_registration_path, class:"btn btn-outline-danger btn-block btn-lg mb-1 font-italic" %>
                </li>
                <li class="mt-sm-2 mr-1">
                  <%= link_to "Log in", new_user_session_path, class:"btn btn-outline-primary btn-block btn-lg mb-1 font-italic" %>
                </li>
              <% end %>
            </ul>
          </div>

        </div>
      </nav>
    </header>

    <main style="margin-bottom:80px">
      <div class="container-fluid  p-lg-5">
        <p class="alert alert-success comment_success shadow">コメントしました</p>
        <p class="alert alert-danger comment_alert shadow">コメントを取り消しました</p>
        <% if notice %>
          <p class="alert alert-success shadow"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger shadow"><%= alert %></p>
        <% end %>
        <div class="mt-sm-3 pr-3 pl-3">
          <%= yield %>
        </div>
      </div>
    </main>

    <footer class="fixed-bottom bg-white shadow", style="height:40px">
      <div class="container">
        <div class="footer_copyright text-center font-italic mt-2">
          © 2021 FoodStorage TatsuyaSato
        </div>
      </div>
    </footer>

  </body>
</html>